### ISSUE TITLE
After updating YACL, Minecraft won't start, but there's a bandaid fix.

### ISSUE THREAD

**Issue by Kissunen** [pupbrained/dropconfirm-modstitch#12]
I'm currently using the Modrinth Launcher with Minecraft 1.21.10 with Fabric loader 0.18.1 and Fabric API 0.138.3+1.21.10, and Modrinth notified that there's an update to YACL, and when I updated YACL from 3.8.0+1.21.9-fabric to 3.8.1+1.21.10-fabric, Minecraft will no longer start. It says DropConfirm requires YACL version 3.8.0, which is the old one for 1.21.9.

Sure, that older YACL for 1.21.9 seems to work fine on 1.21.10, but if you happen to update YACL now, you either have to downgrade it back to 3.8.0 to be able to run the game with this mod, or if you really want to keep the YACL update with the current version of this mod, you can use 7zip (or some other compatible compression software) to extract this mod's drop_confirm-6.0.0.jar file to a temporary folder and then:

The extracted files will include a file called:
fabric.mod.json

Open the fabric.mod.json file in any text editor and find the line 30 which says:
    "yet_another_config_lib_v3": "3.8.0"

Change it to:
    "yet_another_config_lib_v3": "\u003e\u003d3.8.0"

This change will cause dropconfirm to accept YACL as either 3.8.0 or newer. The original setting only allowed 3.8.0 and nothing else, which caused the game to "crash" on start, with the newer YACL 3.8.1 version.

Save the file, compress the contents of your temporary folder back to a zipped file and if needed, remove the .zip suffix and rename it back to drop_confirm-6.0.0.jar

Overwrite the file in the mods folder with the now fixed one and run the game.
It seems to work fine, for now, until this mod gets updated to officially support the newer YACL(s).

Thank you for your work on this mod. It has saved me from many losses, even though I've also changed the drop keybind. With this mod dropping items is twice more safe.

**Comment by skulldogged** [comment]
Should be fixed in 6.1.0, LMK if it's not

**Comment by rumrunner0** [comment]
@skulldogged still exists in 6.1.0 with YACL 3.8.1. I'm on Fabric 1.21.1

**Comment by skulldogged** [comment]
> [@skulldogged](https://github.com/skulldogged) still exists in 6.1.0 with YACL 3.8.1. I'm on Fabric 1.21.1

Yeah, I've noticed myself when playing on latest versions, going to look into it later today

**Comment by skulldogged** [comment]
Should be *actually* fixed in the latest update
